INCLUDE 'EMU8086.INC'
.MODEL SMALL
.STACK 100H


.DATA

MSG1 DB 'ENTER THE NUMBER: ', 0
.CODE         

MAIN PROC   
    
    MOV AX, @DATA
    MOV DS, AX
    LEA SI, MSG1 ; ASK FOR THE NUMBER
    CALL PRINT_STRING ;
    CALL SCAN_NUM ; GET NUMBER IN CX.
    MOV AX, CX ; COPY THE NUMBER TO AX.
    ; PRINT THE FOLLOWING STRING:
    CALL PTHIS
    DB 13, 10, 'YOU HAVE ENTERED: ', 0
    CALL PRINT_NUM ; PRINT NUMBER IN AX.
    DEFINE_SCAN_NUM
    DEFINE_PRINT_STRING
    DEFINE_PRINT_NUM
    DEFINE_PRINT_NUM_UNS ; REQUIRED FOR PRINT_NUM.
    DEFINE_PTHIS
    
ENDP MAIN
END MAIN
